// Converts the Gen 2 species (#152-251) from the pokecrystal disassembly into src/engine/data/gen2.js, in Gen 2's own terms
// (split Special, Gen 2 move and evolution kinds). src/engine/data/gen2_rules.js turns them into Gen 1 rules at load time.
// usage: node tools/convert_gen2.js [path to pokecrystal]   (default vendor/pokecrystal, git-ignored)
'use strict';
const fs = require('fs'), path = require('path');
const ROOT = path.join(__dirname, '..');
const P = path.resolve(process.argv[2] || path.join(ROOT, 'vendor', 'pokecrystal'));
const rd = f => fs.readFileSync(path.join(P, f), 'utf8');
const strip = l => l.split(';')[0].trim();

// dex order: constants/pokemon_constants.asm up to CELEBI
const consts = [];
for (const l of rd('constants/pokemon_constants.asm').split('\n')) {
  const m = l.match(/^\s*const (\w+)/); if (!m) continue;
  if (m[1] === 'EGG') break;
  consts.push(m[1]);
}
const names = [...rd('data/pokemon/names.asm').matchAll(/dname "([^"]*)"/g)].map(m => m[1]);
const dexOf = {}; consts.forEach((c, i) => { dexOf[c] = i + 1; });

// base stats, in dex order via base_stats.asm's INCLUDE list
const statFiles = [...rd('data/pokemon/base_stats.asm').matchAll(/INCLUDE "(data\/pokemon\/base_stats\/[^"]+)"/g)].map(m => m[1]);
function baseStats(file) {
  const raw = rd(file).split('\n'), line = key => strip(raw.find(l => l.includes(key)));
  const nums = raw.map(strip).find(l => /^db\s+\d+,\s*\d+,\s*\d+,\s*\d+,\s*\d+,\s*\d+$/.test(l)).replace(/^db\s+/, '').split(',').map(Number);
  const types = [...new Set(line('; type').replace(/^db\s+/, '').split(',').map(s => s.trim()))];
  const num = key => +line('; ' + key).replace(/^db\s+/, '');
  const growth = line('GROWTH_').replace(/^db\s+GROWTH_/, '');
  const tmhm = strip(raw.find(l => /^\s*tmhm\b/.test(l))).replace(/^tmhm\s*/, '').split(',').map(s => s.trim()).filter(Boolean);
  return { hp: nums[0], atk: nums[1], def: nums[2], spd: nums[3], spa: nums[4], sdf: nums[5], types, catchRate: num('catch rate'), baseExp: num('base exp'), growth, tmhm };
}

// evolutions + level-up moves, in dex order via the pointer table
const evoLabels = [...rd('data/pokemon/evos_attacks_pointers.asm').matchAll(/dw (\w+)/g)].map(m => m[1]);
const blocks = {};
{
  let cur = null;
  for (const raw of rd('data/pokemon/evos_attacks.asm').split('\n')) {
    const lab = raw.match(/^(\w+EvosAttacks):/); if (lab) { cur = blocks[lab[1]] = { evos: [], learn: [], phase: 0 }; continue; }
    const l = strip(raw); if (!cur || !l.startsWith('db')) continue;
    const parts = l.replace(/^db\s+/, '').split(',').map(s => s.trim());
    if (parts[0] === '0') { cur.phase++; continue; }
    if (cur.phase === 0) {
      const [kind, a, b, c] = parts;
      const e = { kind: kind.replace(/^EVOLVE_/, '') };
      if (e.kind === 'LEVEL') Object.assign(e, { level: +a, to: b });
      else if (e.kind === 'ITEM') Object.assign(e, { item: a, to: b });
      else if (e.kind === 'TRADE') Object.assign(e, { item: a === '-1' ? null : a, to: b });
      else if (e.kind === 'HAPPINESS') Object.assign(e, { when: a.replace(/^TR_/, ''), to: b });
      else if (e.kind === 'STAT') Object.assign(e, { level: +a, cmp: { ATK_GT_DEF: 1, ATK_LT_DEF: -1, ATK_EQ_DEF: 0 }[b], to: c });
      else throw new Error('unknown evolution ' + l);
      cur.evos.push(e);
    } else if (cur.phase === 1) cur.learn.push([+parts[0], parts[1]]);
  }
}

// Pokédex category, height, weight
const dexFileOf = {};
for (const m of rd('data/pokemon/dex_entries.asm').matchAll(/(\w+PokedexEntry)::\s*INCLUDE "([^"]+)"/g)) dexFileOf[m[1]] = m[2];
const dexLabels = [...rd('data/pokemon/dex_entry_pointers.asm').matchAll(/dw (\w+PokedexEntry)/g)].map(m => m[1]);
function dexData(i) {
  const src = rd(dexFileOf[dexLabels[i]]);
  const cat = src.match(/db "([^"@]*)@?" ; species name/)[1];
  const [h, w] = src.match(/dw (\d+), (\d+) ; height, weight/).slice(1).map(Number);
  return { cat, ht: [Math.floor(h / 100), h % 100], wt: w };
}

const species = {}, gen1Evos = {};
consts.forEach((id, i) => {
  const b = blocks[evoLabels[i]];
  if (i < 151) { // Gen 1 species: keep only evolutions into Gen 2 species (Golbat -> Crobat, Eevee -> Espeon, ...)
    const add = b.evos.filter(e => dexOf[e.to] > 151);
    if (add.length) gen1Evos[id] = add;
    return;
  }
  species[id] = Object.assign({ id, name: names[i], dex: i + 1 }, baseStats(statFiles[i]), { evos: b.evos, learn: b.learn }, dexData(i));
});
if (Object.keys(species).length !== 100) throw new Error('expected 100 Gen 2 species, got ' + Object.keys(species).length);

const out = '// @ts-nocheck (plain JS moved into a module; typed file by file, see docs/nextjs-migration.md)\nimport { game } from \'../global\';\n\nconst G = game();\n\n// Generated by tools/convert_gen2.js from the pokecrystal disassembly. Gen 2 species #152-251 in Gen 2\'s own terms;\n' +
  '// src/engine/data/gen2_rules.js turns them into Gen 1 rules at load time. Do not edit by hand.\n' +
  'G.GEN2_RAW=' + JSON.stringify({ species, gen1Evos }) + ';\n';
fs.writeFileSync(path.join(ROOT, 'src', 'engine', 'data', 'gen2.ts'), out);
console.log('src/engine/data/gen2.ts:', Object.keys(species).length, 'species,', Object.keys(gen1Evos).length, 'Gen 1 species gaining evolutions,', (out.length / 1024).toFixed(1) + ' KB');

// lint what the game actually loads once src/engine/data/gen2_rules.js has applied Gen 1 rules
const G = require('./headless.js').loadGame({ search: '' }).G, D = G.DATA, problems = [];
const TYPES = new Set(D.typeChart.flatMap(([a, d]) => [a, d]));
const NO_EARLY_ATTACK = new Set(['SMEARGLE', 'WOBBUFFET']); // MIMIC-only and COUNTER-only, like Gen 2
for (const id of Object.keys(species)) {
  const s = D.species[id], lv10 = s.moves1.concat(s.learn.filter(([l]) => l <= 10).map(([, m]) => m));
  if (!s.moves1.length) problems.push(id + ': no starting moves');
  if (!NO_EARLY_ATTACK.has(id) && !lv10.some(m => D.moves[m].power > 0 || m === 'METRONOME')) problems.push(id + ': no attacking move by Lv 10 (' + lv10.join(', ') + ')');
  for (const t of s.types) if (!TYPES.has(t)) problems.push(id + ': unknown type ' + t);
  for (const e of s.evos) {
    if (!D.species[e.to]) problems.push(id + ': evolves into unknown ' + e.to);
    if (e.item && !D.items[e.item]) problems.push(id + ': evolution item ' + e.item + ' missing');
  }
  if (s.name.length > 10) problems.push(id + ': name longer than 10 characters');
  if (D.dexOrder[s.dex] !== id) problems.push(id + ': not at #' + s.dex + ' in the Pokédex order');
}
for (const id of Object.keys(gen1Evos)) for (const e of D.species[id].evos) if (!D.species[e.to]) problems.push(id + ': evolves into unknown ' + e.to);
if (problems.length) { console.error('lint failed:\n  ' + problems.join('\n  ')); process.exit(1); }
console.log('lint: all', Object.keys(species).length, 'species have starting moves, an early attack, known types and valid evolutions');
